server:
  port: 80

spring:
  http:
    multipart:
      max-file-size: 50Mb
      max-request-size: 50Mb

  datasource:
    username: ***
    password: ***
    url: ****
    driver-class-name: com.mysql.cj.jdbc.Driver

